### PR TITLE
fix broken import

### PR DESCRIPTION
**Pull request by josephholsten**
I'm trying to update the ns1 build, but `go get` is failing because of this

### CODE REVIEW

**Comment by pashap** [comment]
@josephholsten What go version are you using? Ive verified with 1.6.2 that the build is working

**Comment by josephholsten** [comment]
```
$ go version
go version go1.7.3 darwin/amd64
```

**Comment by josephholsten** [comment]
alternatively, we could move this `example_test` package to a different directory

**Comment by pashap** [comment]
Sorry @josephholsten, im not seeing any build errors when using 1.7.3:

```
$ go version
go version go1.7.3 darwin/amd64
```

Whats the error that you are seeing, i can keep trying to reproduce it

**Comment by pashap** [comment]
Oh and im using this for reference on testable examples: https://blog.golang.org/examples

**Comment by pashap** [comment]
@josephholsten Is this still an issue for you? I still havent been able to reproduce it.

**Pull request closed without merging**
