### PR TITLE
v2.7.13

### PR DESCRIPTION
**Pull request by ponbiki**
Removes `omitempty` from `tags`

### CODE REVIEW

**Comment by tlkamp** [comment]
@ponbiki hello, the removal of `omitempty` introduced a breaking change to `terraform-provider-ns1` when it was removed from blocked tags. 

Find the attached issue comment: https://github.com/ns1-terraform/terraform-provider-ns1/issues/304#issuecomment-1760666592

I think this PR will introduce the same issue, but now for tags.

**Comment by ponbiki** [comment]
> @ponbiki hello, the removal of `omitempty` introduced a breaking change to `terraform-provider-ns1` when it was removed from blocked tags.
> 
> Find the attached issue comment: [ns1-terraform/terraform-provider-ns1#304 (comment)](https://github.com/ns1-terraform/terraform-provider-ns1/issues/304#issuecomment-1760666592)
> 
> I think this PR will introduce the same issue, but now for tags.

The omitempty needed removed from both unfor

**Comment by tlkamp** [comment]
> The omitempty needed removed from both unfor

@ponbiki Looks like your message was incomplete. Why do they both need removed? Are `tags` and `blocked_tags` now required fields of the API? The documentation does not seem to indicate that.

https://ns1.com/api?docId=2185

The removal of the `omitempty` struct tag is causing your client to send the `blocked_tags` field to the API even when it has no content now where it was not sent before, resulting in the error I reported:

```
Error: POST https://api.nsone.net/v1/zones/MYZONE/MYRECORD/A: 400 tags and blocked_tags must be updated together
```

I believe I'm getting this error because the client is sending an empty list for `blocked_tags` but the `tags` field is not present because it is empty and this PR has not been merged. 

You'll note that I'm able to get past the error if I specify valid values for `tags` and `blocked_tags` in the provider, indicating that the client works fine with the `omitempty` struct tag present.

**Comment by ponbiki** [comment]
> > The omitempty needed removed from both unfor
> 
> @ponbiki Looks like your message was incomplete. Why do they both need removed? Are `tags` and `blocked_tags` now required fields of the API? The documentation does not seem to indicate that.
> 
> https://ns1.com/api?docId=2185
> 
> The removal of the `omitempty` struct tag is causing your client to send the `blocked_tags` field to the API even when it has no content now where it was not sent before, resulting in the error I reported:
> 
> ```
> Error: POST https://api.nsone.net/v1/zones/MYZONE/MYRECORD/A: 400 tags and blocked_tags must be updated together
> ```
> 
> I believe I'm getting this error because the client is sending an empty list for `blocked_tags` but the `tags` field is not present because it is empty and this PR has not been merged.
> 
> You'll note that I'm able to get past the error if I specify valid values for `tags` and `blocked_tags` in the provider, indicating that the client works fine with the `omitempty` struct tag present.

My apologies for the unintended comment post.  The NS1 API requires that if `tags` or `blocked_tags` is POSTed, then the other must also always be POSTed even if said value is `NULL`/`{}`/`[]`.  The `omitempty` was meant to be removed from both `tags` and `blocked_tags` as it was causing the same 400 error to be raised from the API you are seeing (which is because `blocked_tags: NULL` is being sent without corresponding `tags`.  
Edit: This was not a limitation of the original tags design for the self-hosted product (which I believe is documented above).  The tag behavior is slightly different in the managed product.

**Review by pburrows-ns1 — APPROVED** [review]

**Pull request merged**
